services:
  db:
    image: postgis/postgis:16-3.4
    container_name: planpincieux-db
    restart: unless-stopped
    environment: 
      POSTGRES_DB: planpincieux
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [ppcx_net]
    ports:
      - "5434:5432"   # host_port:container_port
    secrets:
      - db_password

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: planpincieux-web
    restart: unless-stopped
    # For developing
    command: python manage.py runserver 0.0.0.0:8000

    # For production (use gunicorn)
    # command: sh -c 'gunicorn planpincieux.wsgi:application -b 0.0.0.0:8000 -w ${GUNICORN_WORKERS:-3} --access-logfile - --error-logfile -'

    depends_on: [db]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: planpincieux
      DB_USER: postgres
      DB_PASSWORD_FILE: /run/secrets/db_password # provided via Docker secret
      SECRET_KEY_FILE: /run/secrets/django_secret_key # provided via Docker secret
      DJANGO_SETTINGS_MODULE: planpincieux.settings
      ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0,150.145.51.193,100.93.90.61
      DEBUG: True
      GUNICORN_WORKERS: "4"

    volumes:
      - ./app:/ppcx/app:rw # Used to edit code on host and directly see changes in container. Not needed in production.
      - dic_data:/ppcx/data:rw # Persistent volume to store h5 DIC data
      - ppcx_data:/data/ppcx_data:ro # Read-only mount of GMG FTP datax
      - fms_data:/ppcx/fms_data:ro # Read-only mount of FMS data # TODO: move it to /data/fms_data for consistency
    ports:
      - "8080:8000"
    networks: [ppcx_net]
    secrets:
      - db_password
      - django_secret_key

networks:
  ppcx_net:
    driver: bridge

volumes:
  db_data:
  dic_data:
  ppcx_data:
    driver_opts:
        type: none
        device: /home/fioli/storage/GMG_ftp/Dati/Planpincieux
        o: bind
  fms_data:
    driver_opts:
          type: none
          device: /home/fioli/storage/fms
          o: bind

secrets:
 db_password: 
  file: ~/secrets/db_password
 django_secret_key: 
  file: ~/secrets/django_secret_key
